export const MAX_ENCHANTS = new Set([
  "Angler VI",
  "Aqua Affinity I",
  "Bane of Arthropods VII",
  "Big Brain V",
  "Blast Protection VII",
  "Blessing VI",
  "Caster VI",
  "Cayenne V",
  "Champion X",
  "Chance V",
  "Charm V",
  "Cleave VI",
  "Compact X",
  "Corruption V",
  "Counter-Strike V",
  "Critical VII",
  "Cubism VI",
  "Cultivating X",
  "Delicate V",
  "Depth Strider III",
  "Divine Gift III",
  "Dragon Hunter V",
  "Dragon Tracer V",
  "Efficiency VI",
  "Efficiency X",
  "Ender Slayer VII",
  "Execute VI",
  "Experience V",
  "Expertise X",
  "Feather Falling X",
  "Feather Falling XX",
  "Ferocious Mana X",
  "Fire Aspect III",
  "Fire Protection VII",
  "First Strike V",
  "Flame II",
  "Fortune IV",
  "Frail VI",
  "Frost Walker II",
  "Giant Killer VII",
  "Growth VII",
  "Hardened Mana X",
  "Harvesting VI",
  "Hecatomb X",
  "Impaling III",
  "Infinite Quiver X",
  "Knockback II",
  "Lethality VI",
  "Life Steal V",
  "Looting V",
  "Luck of the Sea VI",
  "Luck VII",
  "Lure VI",
  "Magnet VI",
  "Mana Steel III",
  "Mana Vampire X",
  "Overload V",
  "Piercing I",
  "Piscary VI",
  "Power VII",
  "Pristine V",
  "Projectile Protection VII",
  "Prosecute VI",
  "Protection VII",
  "Punch II",
  "Rainbow I",
  "Rejuvenate V",
  "Replenish I",
  "Respiration III",
  "Respite V",
  "Scavenger V",
  "Sharpness VII",
  "Silk Touch I",
  "Smarty Pants V",
  "Smelting Touch I",
  "Smite VII",
  "Smoldering V",
  "Snipe IV",
  "Spiked Hook VI",
  "Strong Mana X",
  "Sugar Rush III",
  "Sunder VI",
  "Syphon V",
  "Tabasco III",
  "Thorns III",
  "Thunderbolt VI",
  "Thunderlord VII",
  "Titan Killer VII",
  "Triple-Strike V",
  "True Protection I",
  "Turbo-Cacti V",
  "Turbo-Cane V",
  "Turbo-Carrot V",
  "Turbo-Cocoa V",
  "Turbo-Melon V",
  "Turbo-Mushrooms V",
  "Turbo-Potato V",
  "Turbo-Pumpkin V",
  "Turbo-Warts V",
  "Turbo-Wheat V",
  "Vampirism VI",
  "Venomous VI",
  "Vicious V",
]);
