/**
 * Ordered object of stats
 * @type {{[key:string]: {
 *   name: string
 *   nameLore: string // name found in items lore
 *   nameShort: string // up to 16 chars
 *   nameTiny: string // up to 6 chars
 *   symbol: string
 *   suffix: string
 *   color: string
 * }}}
 */
export const STATS_DATA = {
  health: {
    name: "Health",
    nameLore: "Health",
    nameShort: "Health",
    nameTiny: "HP",
    symbol: "❤",
    suffix: "",
    color: "c",
  },
  defense: {
    name: "Defense",
    nameLore: "Defense",
    nameShort: "Defense",
    nameTiny: "Def",
    symbol: "❈",
    suffix: "",
    color: "a",
  },
  strength: {
    name: "Strength",
    nameLore: "Strength",
    nameShort: "Strength",
    nameTiny: "Str",
    symbol: "❁",
    suffix: "",
    color: "c",
  },
  speed: {
    name: "Speed",
    nameLore: "Speed",
    nameShort: "Speed",
    nameTiny: "Spd",
    symbol: "✦",
    suffix: "",
    color: "f",
  },
  crit_chance: {
    name: "Crit Chance",
    nameLore: "Crit Chance",
    nameShort: "Crit Chance",
    nameTiny: "CC",
    symbol: "☣",
    suffix: "%",
    color: "9",
  },
  crit_damage: {
    name: "Crit Damage",
    nameLore: "Crit Damage",
    nameShort: "Crit Damage",
    nameTiny: "CD",
    symbol: "☠",
    suffix: "%",
    color: "9",
  },
  intelligence: {
    name: "Intelligence",
    nameLore: "Intelligence",
    nameShort: "Intelligence",
    nameTiny: "Int",
    symbol: "✎",
    suffix: "",
    color: "b",
  },
  bonus_attack_speed: {
    name: "Bonus Attack Speed",
    nameLore: "Bonus Attack Speed",
    nameShort: "Attack Speed",
    nameTiny: "Atk",
    symbol: "⚔",
    suffix: "%",
    color: "e",
  },
  sea_creature_chance: {
    name: "Sea Creature Chance",
    nameLore: "Sea Creature Chance",
    nameShort: "SC Chance",
    nameTiny: "SCC",
    symbol: "α",
    suffix: "%",
    color: "3",
  },
  magic_find: {
    name: "Magic Find",
    nameLore: "Magic Find",
    nameShort: "Magic Find",
    nameTiny: "MF",
    symbol: "✯",
    suffix: "",
    color: "b",
  },
  pet_luck: {
    name: "Pet Luck",
    nameLore: "Pet Luck",
    nameShort: "Pet Luck",
    nameTiny: "PL",
    symbol: "♣",
    suffix: "",
    color: "d",
  },
  true_defense: {
    name: "True Defense",
    nameLore: "True Defense",
    nameShort: "True Defense",
    nameTiny: "TD",
    symbol: "❂",
    suffix: "",
    color: "f",
  },
  ferocity: {
    name: "Ferocity",
    nameLore: "Ferocity",
    nameShort: "Ferocity",
    nameTiny: "Frc",
    symbol: "⫽",
    suffix: "",
    color: "c",
  },
  ability_damage: {
    name: "Ability Damage",
    nameLore: "Ability Damage",
    nameShort: "Ability Damage",
    nameTiny: "AD",
    symbol: "๑",
    suffix: "%",
    color: "c",
  },
  mining_speed: {
    name: "Mining Speed",
    nameLore: "Mining Speed",
    nameShort: "Mining Speed",
    nameTiny: "MngSpd",
    symbol: "⸕",
    suffix: "",
    color: "6",
  },
  mining_fortune: {
    name: "Mining Fortune",
    nameLore: "Mining Fortune",
    nameShort: "Mining Fortune",
    nameTiny: "MngFrt",
    symbol: "☘",
    suffix: "",
    color: "6",
  },
  farming_fortune: {
    name: "Farming Fortune",
    nameLore: "Farming Fortune",
    nameShort: "Farming Fortune",
    nameTiny: "FrmFrt",
    symbol: "☘",
    suffix: "",
    color: "6",
  },
  foraging_fortune: {
    name: "Foraging Fortune",
    nameLore: "Foraging Fortune",
    nameShort: "Foraging Fortune",
    nameTiny: "FrgFrt",
    symbol: "☘",
    suffix: "",
    color: "6",
  },
  pristine: {
    name: "Pristine",
    nameLore: "Pristine",
    nameShort: "Pristine",
    nameTiny: "Prs",
    symbol: "✧",
    suffix: "",
    color: "5",
  },
  fishing_speed: {
    name: "Fishing Speed",
    nameLore: "Fishing Speed",
    nameShort: "Fishing Speed",
    nameTiny: "FS",
    symbol: "☂",
    suffix: "",
    color: "b",
  },
  breaking_power: {
    name: "Breaking Power",
    nameLore: "Breaking Power",
    nameShort: "Breaking Power",
    nameTiny: "BP",
    symbol: "Ⓟ",
    suffix: "",
    color: "2",
  },
  health_regen: {
    name: "Health Regen",
    nameLore: "Health Regen",
    nameShort: "Health Regen",
    nameTiny: "HPR",
    symbol: "❣",
    suffix: "",
    color: "c",
  },
  vitality: {
    name: "Vitality",
    nameLore: "Vitality",
    nameShort: "Vitality",
    nameTiny: "Vit",
    symbol: "♨",
    suffix: "",
    color: "5",
  },
  mending: {
    name: "Mending",
    nameLore: "Mending",
    nameShort: "Mending",
    nameTiny: "Mend",
    symbol: "☄",
    suffix: "",
    color: "a",
  },
  // todo: remove this once #1639 is merged and update wisdom values
  wisdom: {
    name: "Wisdom",
    nameLore: "Wisdom",
    nameShort: "Wisdom",
    nameTiny: "W",
    symbol: "☯",
    suffix: "",
    color: "3",
  },
  combat_wisdom: {
    name: "Combat Wisdom",
    nameLore: "Combat Wisdom",
    nameShort: "Combat Wisdom",
    nameTiny: "CW",
    symbol: "☯",
    suffix: "",
    color: "3",
  },
  mana_regen: {
    name: "Mana Regen",
    nameLore: "Mana Regen",
    nameShort: "Mana Regen",
    nameTiny: "MPR",
    symbol: "🗲",
    suffix: "",
    color: "b",
  },
  rift_time: {
    name: "Rift Time",
    nameLore: "Rift Time",
    nameShort: "Rift Time",
    nameTiny: "RT",
    symbol: "ф",
    suffix: "",
    color: "a",
  },
  undead: {
    name: "Undead",
    nameLore: "Undead",
    nameShort: "Undead",
    nameTiny: "U",
    symbol: "༕",
    suffix: "",
    color: "2",
  },
};

const symbols = {
  powder: "᠅",
  soulflow: "⸎",
  dungeon_upgrade: "⚚",
  dye: "✿",
};
for (const stat in STATS_DATA) {
  symbols[stat] = STATS_DATA[stat].symbol;
}
export const SYMBOLS = symbols;

// todo: grab these constants from src/constants/misc: base_stats, stat_template
