export const statNames = {
  Health: "health",
  Defense: "defense",
  Strength: "strength",
  Speed: "speed",
  "Crit Chance": "crit_chance",
  "Crit Damage": "crit_damage",
  "Bonus Attack Speed": "bonus_attack_speed",
  Intelligence: "intelligence",
  "Sea Creature Chance": "sea_creature_chance",
  "Magic Find": "magic_find",
  "Pet Luck": "pet_luck",
  Ferocity: "ferocity",
  "Ability Damage": "ability_damage",
  "Mining Speed": "mining_speed",
  "Mining Fortune": "mining_fortune",
  "Farming Fortune": "farming_fortune",
  "Foraging Fortune": "foraging_fortune",
  Pristine: "pristine",
  "True Defense": "true_defense",
};

export const statNamesShort = {
  ability_damage: "Ability Damage",
  bonus_attack_speed: "Attack Speed",
  crit_chance: "Crit Chance",
  crit_damage: "Crit Damage",
  defense: "Defense",
  farming_fortune: "Farming Fortune",
  ferocity: "Ferocity",
  foraging_fortune: "Foraging Fortune",
  health: "Health",
  intelligence: "Intelligence",
  magic_find: "Magic Find",
  mining_fortune: "Mining Fortune",
  mining_speed: "Mining Speed",
  pet_luck: "Pet Luck",
  pristine: "Pristine",
  sea_creature_chance: "SC Chance",
  speed: "Speed",
  strength: "Strength",
  true_defense: "True Defense",
};

export const stats_symbols = {
  ability_damage: "๑",
  bonus_attack_speed: "⚔",
  crit_chance: "☣",
  crit_damage: "☠",
  defense: "❈",
  farming_fortune: "☘",
  ferocity: "⫽",
  foraging_fortune: "☘",
  health: "❤",
  intelligence: "✎",
  magic_find: "✯",
  mining_fortune: "☘",
  mining_speed: "⸕",
  pet_luck: "♣",
  powder: "᠅", // todo: missing icon in icomoon font
  pristine: "✧",
  sea_creature_chance: "α",
  speed: "✦",
  strength: "❁",
  true_defense: "❂", // todo: missing icon in icomoon font
};

export const statSuffix = {
  ability_damage: "",
  bonus_attack_speed: "%",
  crit_chance: "%",
  crit_damage: "%",
  damage_increase: "",
  damage: "",
  defense: "",
  effective_health: "",
  farming_fortune: "",
  ferocity: "",
  foraging_fortune: "",
  health: "",
  intelligence: "",
  magic_find: "",
  mining_fortune: "",
  mining_speed: "",
  pet_luck: "",
  pristine: "",
  sea_creature_chance: "%",
  speed: "%",
  strength: "",
  true_defense: "",
};
