export const COLLECTION_TYPES = ["farming", "mining", "combat", "foraging", "fishing", "rift"];

export const COLLECTION_DATA = [
  {
    type: "farming",
    skyblockId: "WHEAT",
    name: "Wheat",
    id: 296,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "farming",
    skyblockId: "CARROT_ITEM",
    name: "Carrot",
    id: 391,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "farming",
    skyblockId: "POTATO_ITEM",
    name: "Potato",
    id: 392,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "farming",
    skyblockId: "PUMPKIN",
    name: "Pumpkin",
    id: 86,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "farming",
    skyblockId: "MELON",
    name: "Melon",
    id: 360,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "farming",
    skyblockId: "SEEDS",
    name: "Seeds",
    id: 295,
    damage: 0,
    maxTier: 6,
  },
  {
    type: "farming",
    skyblockId: "MUSHROOM_COLLECTION",
    name: "Mushroom",
    id: 40,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "farming",
    skyblockId: "INK_SACK:3",
    name: "Cocoa Beans",
    id: 351,
    damage: 3,
    maxTier: 9,
  },
  {
    type: "farming",
    skyblockId: "CACTUS",
    name: "Cactus",
    id: 81,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "farming",
    skyblockId: "SUGAR_CANE",
    name: "Sugar Cane",
    id: 338,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "farming",
    skyblockId: "FEATHER",
    name: "Feather",
    id: 288,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "farming",
    skyblockId: "LEATHER",
    name: "Leather",
    id: 334,
    damage: 0,
    maxTier: 10,
  },
  {
    type: "farming",
    skyblockId: "PORK",
    name: "Raw Porkchop",
    id: 319,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "farming",
    skyblockId: "RAW_CHICKEN",
    name: "Raw Chicken",
    id: 365,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "farming",
    skyblockId: "MUTTON",
    name: "Mutton",
    id: 423,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "farming",
    skyblockId: "RABBIT",
    name: "Raw Rabbit",
    id: 411,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "farming",
    skyblockId: "NETHER_STALK",
    name: "Nether Wart",
    id: 372,
    damage: 0,
    maxTier: 9,
  },

  {
    type: "mining",
    skyblockId: "COBBLESTONE",
    name: "Cobblestone",
    id: 4,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "mining",
    skyblockId: "COAL",
    name: "Coal",
    id: 263,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "mining",
    skyblockId: "IRON_INGOT",
    name: "Iron Ingot",
    id: 265,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "mining",
    skyblockId: "GOLD_INGOT",
    name: "Gold Ingot",
    id: 266,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "mining",
    skyblockId: "DIAMOND",
    name: "Diamond",
    id: 264,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "mining",
    skyblockId: "INK_SACK:4",
    name: "Lapis Lazuli",
    id: 351,
    damage: 4,
    maxTier: 9,
  },
  {
    type: "mining",
    skyblockId: "EMERALD",
    name: "Emerald",
    id: 388,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "mining",
    skyblockId: "REDSTONE",
    name: "Redstone",
    id: 331,
    damage: 0,
    maxTier: 11,
  },
  {
    type: "mining",
    skyblockId: "QUARTZ",
    name: "Nether Quartz",
    id: 406,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "mining",
    skyblockId: "OBSIDIAN",
    name: "Obsidian",
    id: 49,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "mining",
    skyblockId: "SAND:1",
    name: "Red Sand",
    id: 12,
    damage: 1,
    maxTier: 8,
  },
  {
    type: "mining",
    skyblockId: "GLOWSTONE_DUST",
    name: "Glowstone",
    id: 348,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "mining",
    skyblockId: "GRAVEL",
    name: "Gravel",
    id: 13,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "mining",
    skyblockId: "ICE",
    name: "Ice",
    id: 79,
    damage: 0,
    maxTier: 10,
  },
  {
    type: "mining",
    skyblockId: "NETHERRACK",
    name: "Netherrack",
    id: 87,
    damage: 0,
    maxTier: 3,
  },
  {
    type: "mining",
    skyblockId: "SAND",
    name: "Sand",
    id: 12,
    damage: 0,
    maxTier: 7,
  },
  {
    type: "mining",
    skyblockId: "ENDER_STONE",
    name: "End Stone",
    id: 121,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "mining",
    skyblockId: "MITHRIL_ORE",
    name: "Mithril",
    id: 138,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "mining",
    skyblockId: "MYCEL",
    name: "Mycelium",
    id: 110,
    damage: 0,
    maxTier: 10,
  },
  {
    type: "mining",
    skyblockId: "HARD_STONE",
    name: "Hard Stone",
    id: 1,
    damage: 0,
    maxTier: 7,
  },
  {
    type: "mining",
    skyblockId: "GEMSTONE_COLLECTION",
    name: "Gemstone",
    texture: "aac15f6fcf2ce963ef4ca71f1a8685adb97eb769e1d11194cbbd2e964a88978c",
    maxTier: 11,
  },
  {
    type: "mining",
    skyblockId: "SULPHUR_ORE",
    name: "Sulphur",
    id: 348,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "combat",
    skyblockId: "ROTTEN_FLESH",
    name: "Rotten Flesh",
    id: 367,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "combat",
    skyblockId: "BONE",
    name: "Bone",
    id: 352,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "combat",
    skyblockId: "STRING",
    name: "String",
    id: 287,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "combat",
    skyblockId: "SPIDER_EYE",
    name: "Spider Eye",
    id: 375,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "combat",
    skyblockId: "SULPHUR",
    name: "Gunpowder",
    id: 289,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "combat",
    skyblockId: "ENDER_PEARL",
    name: "Ender Pearl",
    id: 368,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "combat",
    skyblockId: "GHAST_TEAR",
    name: "Ghast Tear",
    id: 370,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "combat",
    skyblockId: "SLIME_BALL",
    name: "Slimeball",
    id: 341,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "combat",
    skyblockId: "BLAZE_ROD",
    name: "Blaze Rod",
    id: 369,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "combat",
    skyblockId: "MAGMA_CREAM",
    name: "Magma Cream",
    id: 378,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "combat",
    skyblockId: "CHILI_PEPPER",
    name: "Chili Pepper",
    texture: "f859c8df1109c08a756275f1d2887c2748049fe33877769a7b415d56eda469d8",
    maxTier: 9,
  },

  {
    type: "foraging",
    skyblockId: "LOG",
    name: "Oak Wood",
    id: 17,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "foraging",
    skyblockId: "LOG:1",
    name: "Spruce Wood",
    id: 17,
    damage: 1,
    maxTier: 9,
  },
  {
    type: "foraging",
    skyblockId: "LOG:2",
    name: "Birch Wood",
    id: 17,
    damage: 2,
    maxTier: 9,
  },
  {
    type: "foraging",
    skyblockId: "LOG_2:1",
    name: "Dark Oak Wood",
    id: 162,
    damage: 1,
    maxTier: 9,
  },
  {
    type: "foraging",
    skyblockId: "LOG_2",
    name: "Acacia Wood",
    id: 162,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "foraging",
    skyblockId: "LOG:3",
    name: "Jungle Wood",
    id: 17,
    damage: 3,
    maxTier: 9,
  },

  {
    type: "fishing",
    skyblockId: "RAW_FISH",
    name: "Raw Fish",
    id: 349,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "fishing",
    skyblockId: "RAW_FISH:1",
    name: "Raw Salmon",
    id: 349,
    damage: 1,
    maxTier: 9,
  },
  {
    type: "fishing",
    skyblockId: "RAW_FISH:2",
    name: "Clownfish",
    id: 349,
    damage: 2,
    maxTier: 3,
  },
  {
    type: "fishing",
    skyblockId: "RAW_FISH:3",
    name: "Pufferfish",
    id: 349,
    damage: 3,
    maxTier: 6,
  },
  {
    type: "fishing",
    skyblockId: "PRISMARINE_SHARD",
    name: "Prismarine Shard",
    id: 409,
    damage: 0,
    maxTier: 5,
  },
  {
    type: "fishing",
    skyblockId: "PRISMARINE_CRYSTALS",
    name: "Prismarine Crystals",
    id: 410,
    damage: 0,
    maxTier: 7,
  },
  {
    type: "fishing",
    skyblockId: "CLAY_BALL",
    name: "Clay",
    id: 337,
    damage: 0,
    maxTier: 5,
  },
  {
    type: "fishing",
    skyblockId: "WATER_LILY",
    name: "Lily Pad",
    id: 111,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "fishing",
    skyblockId: "INK_SACK",
    name: "Ink Sac",
    id: 351,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "fishing",
    skyblockId: "SPONGE",
    name: "Sponge",
    id: 19,
    damage: 0,
    maxTier: 9,
  },
  {
    type: "fishing",
    skyblockId: "MAGMA_FISH",
    name: "Magmafish",
    texture: "f56b5955b295522c9689481960c01a992ca1c7754cf4ee313c8dd0c356d335f",
    maxTier: 12,
  },
  {
    type: "rift",
    skyblockId: "WILTED_BERBERIS",
    name: "Wilted Berberis",
    id: 32,
    damage: 0,
    maxTier: 4,
  },
  {
    type: "rift",
    skyblockId: "METAL_HEART",
    name: "Living Metal Heart",
    texture: "f0278ee53a53b7733c7b8452fcf794dfbfbc3b032e750a6993573b5bd0299135",
    maxTier: 4,
  },
];
