export const TYPE_TO_CATEGORIES = {
  helmet: ["armor", "helmet"],
  chestplate: ["armor", "chestplate"],
  leggings: ["armor", "leggings"],
  boots: ["armor", "boots"],
  sword: ["weapon", "sword"],
  bow: ["weapon", "bow"],
  longsword: ["weapon", "longsword"],
  wand: ["weapon", "wand"],
  hatccessory: ["armor", "helmet", "accessory", "hatccessory"],
  gauntlet: ["weapon", "mining_tool", "tool", "gauntlet"],
  pickaxe: ["mining_tool", "tool", "pickaxe"],
  drill: ["mining_tool", "tool", "drill"],
  axe: ["foraging_tool", "tool", "axe"],
  hoe: ["farming_tool", "tool", "hoe"],
  "fishing rod": ["fishing_tool", "tool"],
  "fishing weapon": ["fishing_tool", "tool", "weapon"],
  shovel: ["tool", "shovel"],
  shears: ["tool", "shears"],
  bait: ["bait"],
  item: ["item"],
  accessory: ["accessory"],
  arrow: ["arrow"],
  "reforge stone": ["reforge_stone"],
  cosmetic: ["cosmetic"],
  "pet item": ["pet_item"],
  "travel scroll": ["travel_scroll"],
  belt: ["belt"],
  cloak: ["cloak"],
  necklace: ["necklace"],
  gloves: ["gloves"],
  bracelet: ["bracelet"],
  deployable: ["deployable"],
  "trophy fish": ["trophy_fish"],
};

export const ENCHANTMENTS_TO_CATEGORIES = {
  farming_tool: [
    "delicate",
    "harvesting",
    "cultivating",
    "replenish",
    "turbo_cacti",
    "turbo_cane",
    "turbo_carrot",
    "turbo_mushrooms",
    "turbo_potato",
    "turbo_warts",
    "turbo_wheat",
    "sunder",
  ],
};
