const categoryInventory = [
  {
    display_name: "Go Back",
    id: 262,
    damage: 0,
    rarity: "uncommon",
    tag: {
      display: {
        Lore: [],
      },
    },
    position: 48,
  },
  {
    display_name: "Close",
    id: 166,
    damage: 0,
    rarity: "special",
    tag: {
      display: {
        Lore: [],
      },
    },
    position: 49,
  },
  {
    display_name: "Next Page",
    id: 262,
    damage: 0,
    rarity: "uncommon",
    tag: {
      display: {
        Lore: [],
      },
    },
    position: 53,
  },
];

export const MUSEUM = {
  weapons: [
    "ROGUE_SWORD",
    "FANCY_SWORD",
    "SPIDER_SWORD",
    "UNDEAD_SWORD",
    "ARTISANAL_SHORTBOW",
    "END_SWORD",
    "CLEAVER",
    "FLAMING_SWORD",
    "WITHER_BOW",
    "DECENT_BOW",
    "HUNTER_KNIFE",
    "SAVANA_BOW",
    "PRISMARINE_BOW",
    "PRISMARINE_BLADE",
    "ENDER_BOW",
    "SILVER_FANG",
    "CRYPT_DREADLORD_SWORD",
    "ZOMBIE_SOLDIER_CUTLASS",
    "MACHINE_GUN_BOW",
    "MERCENARY_AXE",
    "STARLIGHT_WAND",
    "ARACK",
    "TACTICIAN_SWORD",
    "SNIPER_BOW",
    "CRYPT_BOW",
    "FROZEN_SCYTHE",
    "GLACIAL_SCYTHE",
    "GOLEM_SWORD",
    "RAIDER_AXE",
    "EXPLOSIVE_BOW",
    "MAGMA_BOW",
    "SLIME_BOW",
    "EARTH_SHARD",
    "VOIDWALKER_KATANA",
    "VOIDEDGE_KATANA",
    "VORPAL_KATANA",
    "ATOMSPLIT_KATANA",
    "SINSEEKER_SCYTHE",
    "VOID_SWORD",
    "DRAGON_SHORTBOW",
    "ASPECT_OF_THE_END",
    "ASPECT_OF_THE_VOID",
    "SCORPION_BOW",
    "HURRICANE_BOW",
    "END_STONE_BOW",
    "REVENANT_SWORD",
    "REAPER_SWORD",
    "AXE_OF_THE_SHREDDED",
    "RECLUSE_FANG",
    "CONJURING_SWORD",
    "ZOMBIE_COMMANDER_WHIP",
    "EDIBLE_MACE",
    "ZOMBIE_SWORD",
    "ORNATE_ZOMBIE_SWORD",
    "FLORID_ZOMBIE_SWORD",
    "SCORPION_FOIL",
    "END_STONE_SWORD",
    "DEATH_BOW",
    "GIANT_CLEAVER",
    "SPIDER_QUEENS_STINGER",
    "VENOMS_TOUCH",
    "SHAMAN_SWORD",
    "POOCH_SWORD",
    "EMERALD_BLADE",
    "INK_WAND",
    "ZOMBIE_KNIGHT_SWORD",
    "FEL_SWORD",
    "SOULS_REBOUND",
    "JUJU_SHORTBOW",
    "LEAPING_SWORD",
    "SILK_EDGE_SWORD",
    "BONZO_STAFF",
    "SILENT_DEATH",
    "STONE_BLADE",
    "RUNAANS_BOW",
    "MOSQUITO_BOW",
    "SPIRIT_SWORD",
    "BAT_WAND",
    "ITEM_SPIRIT_BOW",
    "BONE_BOOMERANG",
    "SWORD_OF_REVELATIONS",
    "SOUL_WHIP",
    "ASPECT_OF_THE_DRAGON",
    "PIGMAN_SWORD",
    "MIDAS_SWORD",
    "MIDAS_STAFF",
    "YETI_SWORD",
    "LAST_BREATH",
    "ICE_SPRAY_WAND",
    "LIVID_DAGGER",
    "SHADOW_FURY",
    "REAPER_SCYTHE",
    "GEMSTONE_GAUNTLET",
    "DAEDALUS_AXE",
    "PHANTOM_ROD",
    "VOODOO_DOLL",
    "FLOWER_OF_TRUTH",
    "WITHER_CLOAK",
    "NECROMANCER_SWORD",
    "GIANTS_SWORD",
    "TERMINATOR",
    "HYPERION",
    "ASTRAEA",
    "SCYLLA",
    "VALKYRIE",
    "BLADE_OF_THE_VOLCANO",
    "FIRE_VEIL_WAND",
    "STAFF_OF_THE_VOLCANO",
    "FIRE_FURY_STAFF",
    "FIRE_FREEZE_STAFF",
    "SULPHUR_BOW",
    "WAND_OF_STRENGTH",
    "RAGNAROCK_AXE",
    "ALCHEMISTS_STAFF",
    "SWORD_OF_BAD_HEALTH",
    "ENRAGER",
    "HOLLOW_WAND",
    "FIREDUST_DAGGER",
    "BURSTFIRE_DAGGER",
    "HEARTFIRE_DAGGER",
    "MAWDUST_DAGGER",
    "BURSTMAW_DAGGER",
    "HEARTMAW_DAGGER",
    "DARK_CLAYMORE",
  ],
  armor: [
    "FARM_SUIT",
    "MUSHROOM",
    "ANGLER",
    "PUMPKIN",
    "CACTUS",
    "LEAFLET",
    "LAPIS_ARMOR",
    "MINER_OUTFIT",
    "GOLEM_ARMOR",
    "TANK_MINER",
    "ROTTEN",
    "HARDENED_DIAMOND",
    "MINERAL",
    "FAIRY",
    "FARM_ARMOR",
    "MERCENARY",
    "STARLIGHT",
    "ARACHNE",
    "BOUNCY",
    "HEAVY",
    "SKELETON_GRUNT",
    "GROWTH",
    "SALMON_NEW",
    "MONSTER_HUNTER",
    "SKELETON_SOLDIER",
    "ZOMBIE_SOLDIER",
    "GOBLIN",
    "HEAT",
    "FLAME_BREAKER",
    "ARMOR_OF_YOG",
    "END",
    "ARMOR_OF_THE_PACK",
    "ARMOR_OF_MAGMA",
    "EMERALD_ARMOR",
    "EMBER",
    "CRYSTAL",
    "SKELETON_MASTER",
    "ZOMBIE",
    "REVENANT",
    "REAPER",
    "BLAZE",
    "FROZEN_BLAZE",
    "CHEAP_TUXEDO",
    "FANCY_TUXEDO",
    "ELEGANT_TUXEDO",
    "SPEEDSTER",
    "SPONGE",
    "MASTIFF",
    "TARANTULA",
    "SPOOKY",
    "SNOW_SUIT",
    "NUTCRACKER",
    "GLACITE",
    "ZOMBIE_KNIGHT",
    "ZOMBIE_COMMANDER",
    "SHARK_SCALE",
    "BAT_PERSON",
    "DIVER",
    "WEREWOLF",
    "ADAPTIVE",
    "YOUNG_DRAGON",
    "OLD_DRAGON",
    "WISE_DRAGON",
    "PROTECTOR_DRAGON",
    "STRONG_DRAGON",
    "UNSTABLE_DRAGON",
    "HOLY_DRAGON",
    "SUPER_HEAVY",
    "SKELETOR",
    "SKELETON_LORD",
    "ZOMBIE_LORD",
    "PERFECT_TIER_12",
    "SUPERIOR_DRAGON",
    "SORROW",
    "SHADOW_ASSASSIN",
    "FINAL_DESTINATION",
    "DIVAN",
    "NECROMANCER_LORD",
    "WITHER",
    "TANK_WITHER",
    "WISE_WITHER",
    "SPEED_WITHER",
    "POWER_WITHER",
    "RAMPART",
    "REKINDLED_EMBER",
    "SHIMMERING_LIGHT",
    "BERSERKER",
    "LAVA_SEA_CREATURE",
    "THUNDER",
    "MAGMA_LORD",
    "BRONZE_HUNTER",
    "SILVER_HUNTER",
    "GOLD_HUNTER",
    "DIAMOND_HUNTER",
    "MAGMA",
    "VANQUISHED",
    "MOLTEN",
    "AURORA",
    "CRIMSON",
    "FERVOR",
    "TERROR",
    "HOLLOW",
    "MELON",
    "CROPIE",
    "SQUASH",
    "FERMENTO",
    "RABBIT",
    "SEYMOUR",
    "LOTUS",
  ],
  rarities: [
    "ENCHANTED_JACK_O_LANTERN",
    "OBSIDIAN_CHESTPLATE",
    "SQUID_BOOTS",
    "BONZO_MASK",
    "SPIRIT_MASK",
    "WATER_HYDRA_HEAD",
    "VAMPIRE_MASK",
    "WITCH_MASK",
    "VAMPIRE_WITCH_MASK",
    "JERRY_STAFF",
    "FARMER_BOOTS",
    "RANCHERS_BOOTS",
    "STONK_PICKAXE",
    "JUNGLE_AXE",
    "TREECAPITATOR_AXE",
    "MITHRIL_COAT",
    "THORNS_BOOTS",
    "RADIANT_POWER_ORB",
    "MANA_FLUX_POWER_ORB",
    "OVERFLUX_POWER_ORB",
    "PLASMAFLUX_POWER_ORB",
    "WEIRD_TUBA",
    "ZOMBIE_HEART",
    "CRYSTALLIZED_HEART",
    "REVIVED_HEART",
    "KRAMPUS_HELMET",
    "RIFT_NECKLACE_OUTSIDE",
    "SUPER_COMPACTOR_3000",
    "ROD_OF_THE_SEA",
    "PRECURSOR_EYE",
    "SUMMONING_RING",
    "REAPER_MASK",
    "THE_SHREDDER",
    "YETI_ROD",
    "AUGER_ROD",
    "WARDEN_HELMET",
    "CROWN_OF_GREED",
    "GYROKINETIC_WAND",
    "WAND_OF_HEALING",
    "WAND_OF_MENDING",
    "WAND_OF_RESTORATION",
    "WAND_OF_ATONEMENT",
    "MITHRIL_DRILL_1",
    "MITHRIL_DRILL_2",
    "GEMSTONE_DRILL_1",
    "GEMSTONE_DRILL_2",
    "GEMSTONE_DRILL_3",
    "GEMSTONE_DRILL_4",
    "TITANIUM_DRILL_1",
    "TITANIUM_DRILL_2",
    "TITANIUM_DRILL_3",
    "TITANIUM_DRILL_4",
    "STEEL_CHESTPLATE",
    "MENDER_CROWN",
    "WITHER_GOGGLES",
    "FLAMING_FIST",
    "IMPLOSION_BELT",
    "GAUNTLET_OF_CONTAGION",
    "SCOVILLE_BELT",
    "SCOURGE_CLOAK",
    "DELIRIUM_NECKLACE",
    "LAVA_SHELL_NECKLACE",
    "STARTER_LAVA_ROD",
    "MAGMA_ROD",
    "INFERNO_ROD",
    "HELLFIRE_ROD",
    "DOJO_BLACK_BELT",
    "SYNTHESIZER_V3",
    "ANCIENT_CLOAK",
    "THEORETICAL_HOE_WHEAT_1",
    "THEORETICAL_HOE_WHEAT_2",
    "THEORETICAL_HOE_WHEAT_3",
    "THEORETICAL_HOE_CARROT_1",
    "THEORETICAL_HOE_CARROT_2",
    "THEORETICAL_HOE_CARROT_3",
    "THEORETICAL_HOE_POTATO_1",
    "THEORETICAL_HOE_POTATO_2",
    "THEORETICAL_HOE_POTATO_3",
    "THEORETICAL_HOE_WARTS_1",
    "THEORETICAL_HOE_WARTS_2",
    "THEORETICAL_HOE_WARTS_3",
    "THEORETICAL_HOE_CANE_1",
    "THEORETICAL_HOE_CANE_2",
    "THEORETICAL_HOE_CANE_3",
    "CACTUS_KNIFE",
    "FUNGI_CUTTER",
    "COCO_CHOPPER",
    "MELON_DICER",
    "MELON_DICER_2",
    "MELON_DICER_3",
    "PUMPKIN_DICER",
    "PUMPKIN_DICER_2",
    "PUMPKIN_DICER_3",
    "SOS_FLARE",
    "TACTICAL_INSERTION",
    "ANNIHILATION_CLOAK",
    "BLAZETEKK_HAM_RADIO",
    "DEMONLORD_GAUNTLET",
  ],
  children: {
    // Weapons
    GLACIAL_SCYTHE: "FROZEN_SCYTHE",
    VOIDEDGE_KATANA: "VOIDWALKER_KATANA",
    VORPAL_KATANA: "VOIDEDGE_KATANA",
    ATOMSPLIT_KATANA: "VORPAL_KATANA",
    ASPECT_OF_THE_VOID: "ASPECT_OF_THE_END",
    REAPER_SWORD: "REVENANT_SWORD",
    AXE_OF_THE_SHREDDED: "REAPER_SWORD",
    ORNATE_ZOMBIE_SWORD: "ZOMBIE_SWORD",
    FLORID_ZOMBIE_SWORD: "ORNATE_ZOMBIE_SWORD",
    POOCH_SWORD: "SHAMAN_SWORD",
    SILK_EDGE_SWORD: "LEAPING_SWORD",
    // Armor
    MINERAL: "HARDENED_DIAMOND",
    MASTIFF: "GROWTH",
    FLAME_BREAKER: "HEAT",
    ARMOR_OF_YOG: "FLAME_BREAKER",
    REVENANT: "ZOMBIE",
    REAPER: "REVENANT",
    FROZEN_BLAZE: "BLAZE",
    FANCY_TUXEDO: "CHEAP_TUXEDO",
    ELEGANT_TUXEDO: "FANCY_TUXEDO",
    SHARK_SCALE: "SPONGE",
    BAT_PERSON: "SPOOKY",
    SILVER_HUNTER: "BRONZE_HUNTER",
    GOLD_HUNTER: "SILVER_HUNTER",
    DIAMOND_HUNTER: "GOLD_HUNTER",
    VANQUISHED: "MAGMA",
    CROPIE: "MELON",
    SQUASH: "CROPIE",
    FERMENTO: "SQUASH",
    // Rarities
    WITCH_MASK: "VAMPIRE_MASK",
    VAMPIRE_WITCH_MASK: "WITCH_MASK",
    RANCHERS_BOOTS: "FARMER_BOOTS",
    TREECAPITATOR_AXE: "JUNGLE_AXE",
    MANA_FLUX_POWER_ORB: "RADIANT_POWER_ORB",
    OVERFLUX_POWER_ORB: "MANA_FLUX_POWER_ORB",
    PLASMAFLUX_POWER_ORB: "OVERFLUX_POWER_ORB",
    CRYSTALLIZED_HEART: "ZOMBIE_HEART",
    REVIVED_HEART: "CRYSTALLIZED_HEART",
    WAND_OF_MENDING: "WAND_OF_HEALING",
    WAND_OF_RESTORATION: "WAND_OF_MENDING",
    WAND_OF_ATONEMENT: "WAND_OF_RESTORATION",
    MITHRIL_DRILL_2: "MITHRIL_DRILL_1",
    GEMSTONE_DRILL_2: "GEMSTONE_DRILL_1",
    GEMSTONE_DRILL_3: "GEMSTONE_DRILL_2",
    GEMSTONE_DRILL_4: "GEMSTONE_DRILL_3",
    TITANIUM_DRILL_2: "TITANIUM_DRILL_1",
    TITANIUM_DRILL_3: "TITANIUM_DRILL_2",
    TITANIUM_DRILL_4: "TITANIUM_DRILL_3",
    DIVAN_DRILL: "TITANIUM_DRILL_4",
    INFERNO_ROD: "MAGMA_ROD",
    HELLFIRE_ROD: "INFERNO_ROD",
    BURSTMAW_DAGGER: "MAWDUST_DAGGER",
    HEARTMAW_DAGGER: "BURSTMAW_DAGGER",
    BURSTFIRE_DAGGER: "FIREDUST_DAGGER",
    HEARTFIRE_DAGGER: "BURSTFIRE_DAGGER",
    MELON_DICER_2: "MELON_DICER",
    MELON_DICER_3: "MELON_DICER_2",
    PUMPKIN_DICER_2: "PUMPKIN_DICER",
    PUMPKIN_DICER_3: "PUMPKIN_DICER_2",
    THEORETICAL_HOE_WHEAT_2: "THEORETICAL_HOE_WHEAT_1",
    THEORETICAL_HOE_WHEAT_3: "THEORETICAL_HOE_WHEAT_2",
    THEORETICAL_HOE_CARROT_2: "THEORETICAL_HOE_CARROT_1",
    THEORETICAL_HOE_CARROT_3: "THEORETICAL_HOE_CARROT_2",
    THEORETICAL_HOE_POTATO_2: "THEORETICAL_HOE_POTATO_1",
    THEORETICAL_HOE_POTATO_3: "THEORETICAL_HOE_POTATO_2",
    THEORETICAL_HOE_WARTS_2: "THEORETICAL_HOE_WARTS_1",
    THEORETICAL_HOE_WARTS_3: "THEORETICAL_HOE_WARTS_2",
    THEORETICAL_HOE_CANE_2: "THEORETICAL_HOE_CANE_1",
    THEORETICAL_HOE_CANE_3: "THEORETICAL_HOE_CANE_2",
  },
  armor_to_id: {
    FARM_SUIT: ["FARM_SUIT_HELMET", "FARM_SUIT_CHESTPLATE", "FARM_SUIT_LEGGINGS", "FARM_SUIT_BOOTS"],
    MUSHROOM: ["MUSHROOM_HELMET", "MUSHROOM_CHESTPLATE", "MUSHROOM_LEGGINGS", "MUSHROOM_BOOTS"],
    ANGLER: ["ANGLER_HELMET", "ANGLER_CHESTPLATE", "ANGLER_LEGGINGS", "ANGLER_BOOTS"],
    PUMPKIN: ["PUMPKIN_HELMET", "PUMPKIN_CHESTPLATE", "PUMPKIN_LEGGINGS", "PUMPKIN_BOOTS"],
    CACTUS: ["CACTUS_HELMET", "CACTUS_CHESTPLATE", "CACTUS_LEGGINGS", "CACTUS_BOOTS"],
    LEAFLET: ["LEAFLET_HELMET", "LEAFLET_CHESTPLATE", "LEAFLET_LEGGINGS", "LEAFLET_BOOTS"],
    LAPIS_ARMOR: ["LAPIS_ARMOR_HELMET", "LAPIS_ARMOR_CHESTPLATE", "LAPIS_ARMOR_LEGGINGS", "LAPIS_ARMOR_BOOTS"],
    MINER_OUTFIT: ["MINER_OUTFIT_HELMET", "MINER_OUTFIT_CHESTPLATE", "MINER_OUTFIT_LEGGINGS", "MINER_OUTFIT_BOOTS"],
    GOLEM_ARMOR: ["GOLEM_ARMOR_HELMET", "GOLEM_ARMOR_CHESTPLATE", "GOLEM_ARMOR_LEGGINGS", "GOLEM_ARMOR_BOOTS"],
    TANK_MINER: ["TANK_MINER_HELMET", "TANK_MINER_CHESTPLATE", "TANK_MINER_LEGGINGS", "TANK_MINER_BOOTS"],
    ROTTEN: ["ROTTEN_HELMET", "ROTTEN_CHESTPLATE", "ROTTEN_LEGGINGS", "ROTTEN_BOOTS"],
    HARDENED_DIAMOND: [
      "HARDENED_DIAMOND_HELMET",
      "HARDENED_DIAMOND_CHESTPLATE",
      "HARDENED_DIAMOND_LEGGINGS",
      "HARDENED_DIAMOND_BOOTS",
    ],
    MINERAL: ["MINERAL_HELMET", "MINERAL_CHESTPLATE", "MINERAL_LEGGINGS", "MINERAL_BOOTS"],
    FAIRY: ["FAIRY_HELMET", "FAIRY_CHESTPLATE", "FAIRY_LEGGINGS", "FAIRY_BOOTS"],
    FARM_ARMOR: ["FARM_ARMOR_HELMET", "FARM_ARMOR_CHESTPLATE", "FARM_ARMOR_LEGGINGS", "FARM_ARMOR_BOOTS"],
    MERCENARY: ["MERCENARY_HELMET", "MERCENARY_CHESTPLATE", "MERCENARY_LEGGINGS", "MERCENARY_BOOTS"],
    STARLIGHT: ["STARLIGHT_HELMET", "STARLIGHT_CHESTPLATE", "STARLIGHT_LEGGINGS", "STARLIGHT_BOOTS"],
    ARACHNE: ["ARACHNE_HELMET", "ARACHNE_CHESTPLATE", "ARACHNE_LEGGINGS", "ARACHNE_BOOTS"],
    BOUNCY: ["BOUNCY_HELMET", "BOUNCY_CHESTPLATE", "BOUNCY_LEGGINGS", "BOUNCY_BOOTS"],
    HEAVY: ["HEAVY_HELMET", "HEAVY_CHESTPLATE", "HEAVY_LEGGINGS", "HEAVY_BOOTS"],
    SKELETON_GRUNT: [
      "SKELETON_GRUNT_HELMET",
      "SKELETON_GRUNT_CHESTPLATE",
      "SKELETON_GRUNT_LEGGINGS",
      "SKELETON_GRUNT_BOOTS",
    ],
    GROWTH: ["GROWTH_HELMET", "GROWTH_CHESTPLATE", "GROWTH_LEGGINGS", "GROWTH_BOOTS"],
    SALMON_NEW: ["SALMON_HELMET_NEW", "SALMON_CHESTPLATE_NEW", "SALMON_LEGGINGS_NEW", "SALMON_BOOTS_NEW"],
    MONSTER_HUNTER: ["SKELETON_HELMET", "GUARDIAN_CHESTPLATE", "CREEPER_LEGGINGS", "SPIDER_BOOTS"],
    SKELETON_SOLDIER: [
      "SKELETON_SOLDIER_HELMET",
      "SKELETON_SOLDIER_CHESTPLATE",
      "SKELETON_SOLDIER_LEGGINGS",
      "SKELETON_SOLDIER_BOOTS",
    ],
    ZOMBIE_SOLDIER: [
      "ZOMBIE_SOLDIER_HELMET",
      "ZOMBIE_SOLDIER_CHESTPLATE",
      "ZOMBIE_SOLDIER_LEGGINGS",
      "ZOMBIE_SOLDIER_BOOTS",
    ],
    GOBLIN: ["GOBLIN_HELMET", "GOBLIN_CHESTPLATE", "GOBLIN_LEGGINGS", "GOBLIN_BOOTS"],
    HEAT: ["HEAT_HELMET", "HEAT_CHESTPLATE", "HEAT_LEGGINGS", "HEAT_BOOTS"],
    FLAME_BREAKER: [
      "FLAME_BREAKER_HELMET",
      "FLAME_BREAKER_CHESTPLATE",
      "FLAME_BREAKER_LEGGINGS",
      "FLAME_BREAKER_BOOTS",
    ],
    ARMOR_OF_YOG: ["ARMOR_OF_YOG_HELMET", "ARMOR_OF_YOG_CHESTPLATE", "ARMOR_OF_YOG_LEGGINGS", "ARMOR_OF_YOG_BOOTS"],
    END: ["END_HELMET", "END_CHESTPLATE", "END_LEGGINGS", "END_BOOTS"],
    ARMOR_OF_THE_PACK: ["HELMET_OF_THE_PACK", "CHESTPLATE_OF_THE_PACK", "LEGGINGS_OF_THE_PACK", "BOOTS_OF_THE_PACK"],
    ARMOR_OF_MAGMA: [
      "ARMOR_OF_MAGMA_HELMET",
      "ARMOR_OF_MAGMA_CHESTPLATE",
      "ARMOR_OF_MAGMA_LEGGINGS",
      "ARMOR_OF_MAGMA_BOOTS",
    ],
    EMERALD_ARMOR: [
      "EMERALD_ARMOR_HELMET",
      "EMERALD_ARMOR_CHESTPLATE",
      "EMERALD_ARMOR_LEGGINGS",
      "EMERALD_ARMOR_BOOTS",
    ],
    EMBER: ["EMBER_HELMET", "EMBER_CHESTPLATE", "EMBER_LEGGINGS", "EMBER_BOOTS"],
    CRYSTAL: ["CRYSTAL_HELMET", "CRYSTAL_CHESTPLATE", "CRYSTAL_LEGGINGS", "CRYSTAL_BOOTS"],
    SKELETON_MASTER: [
      "SKELETON_MASTER_HELMET",
      "SKELETON_MASTER_CHESTPLATE",
      "SKELETON_MASTER_LEGGINGS",
      "SKELETON_MASTER_BOOTS",
    ],
    ZOMBIE: ["ZOMBIE_CHESTPLATE", "ZOMBIE_LEGGINGS", "ZOMBIE_BOOTS"],
    REVENANT: ["REVENANT_CHESTPLATE", "REVENANT_LEGGINGS", "REVENANT_BOOTS"],
    REAPER: ["REAPER_CHESTPLATE", "REAPER_LEGGINGS", "REAPER_BOOTS"],
    BLAZE: ["BLAZE_HELMET", "BLAZE_CHESTPLATE", "BLAZE_LEGGINGS", "BLAZE_BOOTS"],
    FROZEN_BLAZE: ["FROZEN_BLAZE_HELMET", "FROZEN_BLAZE_CHESTPLATE", "FROZEN_BLAZE_LEGGINGS", "FROZEN_BLAZE_BOOTS"],
    CHEAP_TUXEDO: ["CHEAP_TUXEDO_CHESTPLATE", "CHEAP_TUXEDO_LEGGINGS", "CHEAP_TUXEDO_BOOTS"],
    FANCY_TUXEDO: ["FANCY_TUXEDO_CHESTPLATE", "FANCY_TUXEDO_LEGGINGS", "FANCY_TUXEDO_BOOTS"],
    ELEGANT_TUXEDO: ["ELEGANT_TUXEDO_CHESTPLATE", "ELEGANT_TUXEDO_LEGGINGS", "ELEGANT_TUXEDO_BOOTS"],
    SPEEDSTER: ["SPEEDSTER_HELMET", "SPEEDSTER_CHESTPLATE", "SPEEDSTER_LEGGINGS", "SPEEDSTER_BOOTS"],
    SPONGE: ["SPONGE_HELMET", "SPONGE_CHESTPLATE", "SPONGE_LEGGINGS", "SPONGE_BOOTS"],
    MASTIFF: ["MASTIFF_HELMET", "MASTIFF_CHESTPLATE", "MASTIFF_LEGGINGS", "MASTIFF_BOOTS"],
    TARANTULA: ["TARANTULA_HELMET", "TARANTULA_CHESTPLATE", "TARANTULA_LEGGINGS", "TARANTULA_BOOTS"],
    SPOOKY: ["SPOOKY_HELMET", "SPOOKY_CHESTPLATE", "SPOOKY_LEGGINGS", "SPOOKY_BOOTS"],
    SNOW_SUIT: ["SNOW_SUIT_HELMET", "SNOW_SUIT_CHESTPLATE", "SNOW_SUIT_LEGGINGS", "SNOW_SUIT_BOOTS"],
    NUTCRACKER: ["NUTCRACKER_HELMET", "NUTCRACKER_CHESTPLATE", "NUTCRACKER_LEGGINGS", "NUTCRACKER_BOOTS"],
    GLACITE: ["GLACITE_HELMET", "GLACITE_CHESTPLATE", "GLACITE_LEGGINGS", "GLACITE_BOOTS"],
    ZOMBIE_KNIGHT: [
      "ZOMBIE_KNIGHT_HELMET",
      "ZOMBIE_KNIGHT_CHESTPLATE",
      "ZOMBIE_KNIGHT_LEGGINGS",
      "ZOMBIE_KNIGHT_BOOTS",
    ],
    ZOMBIE_COMMANDER: [
      "ZOMBIE_COMMANDER_HELMET",
      "ZOMBIE_COMMANDER_CHESTPLATE",
      "ZOMBIE_COMMANDER_LEGGINGS",
      "ZOMBIE_COMMANDER_BOOTS",
    ],
    SHARK_SCALE: ["SHARK_SCALE_HELMET", "SHARK_SCALE_CHESTPLATE", "SHARK_SCALE_LEGGINGS", "SHARK_SCALE_BOOTS"],
    BAT_PERSON: ["BAT_PERSON_HELMET", "BAT_PERSON_CHESTPLATE", "BAT_PERSON_LEGGINGS", "BAT_PERSON_BOOTS"],
    DIVER: ["DIVER_HELMET", "DIVER_CHESTPLATE", "DIVER_LEGGINGS", "DIVER_BOOTS"],
    WEREWOLF: ["WEREWOLF_HELMET", "WEREWOLF_CHESTPLATE", "WEREWOLF_LEGGINGS", "WEREWOLF_BOOTS"],
    ADAPTIVE: ["ADAPTIVE_HELMET", "ADAPTIVE_CHESTPLATE", "ADAPTIVE_LEGGINGS", "ADAPTIVE_BOOTS"],
    YOUNG_DRAGON: ["YOUNG_DRAGON_HELMET", "YOUNG_DRAGON_CHESTPLATE", "YOUNG_DRAGON_LEGGINGS", "YOUNG_DRAGON_BOOTS"],
    OLD_DRAGON: ["OLD_DRAGON_HELMET", "OLD_DRAGON_CHESTPLATE", "OLD_DRAGON_LEGGINGS", "OLD_DRAGON_BOOTS"],
    WISE_DRAGON: ["WISE_DRAGON_HELMET", "WISE_DRAGON_CHESTPLATE", "WISE_DRAGON_LEGGINGS", "WISE_DRAGON_BOOTS"],
    PROTECTOR_DRAGON: [
      "PROTECTOR_DRAGON_HELMET",
      "PROTECTOR_DRAGON_CHESTPLATE",
      "PROTECTOR_DRAGON_LEGGINGS",
      "PROTECTOR_DRAGON_BOOTS",
    ],
    STRONG_DRAGON: [
      "STRONG_DRAGON_HELMET",
      "STRONG_DRAGON_CHESTPLATE",
      "STRONG_DRAGON_LEGGINGS",
      "STRONG_DRAGON_BOOTS",
    ],
    UNSTABLE_DRAGON: [
      "UNSTABLE_DRAGON_HELMET",
      "UNSTABLE_DRAGON_CHESTPLATE",
      "UNSTABLE_DRAGON_LEGGINGS",
      "UNSTABLE_DRAGON_BOOTS",
    ],
    HOLY_DRAGON: ["HOLY_DRAGON_HELMET", "HOLY_DRAGON_CHESTPLATE", "HOLY_DRAGON_LEGGINGS", "HOLY_DRAGON_BOOTS"],
    SUPER_HEAVY: ["SUPER_HEAVY_HELMET", "SUPER_HEAVY_CHESTPLATE", "SUPER_HEAVY_LEGGINGS", "SUPER_HEAVY_BOOTS"],
    SKELETOR: ["SKELETOR_HELMET", "SKELETOR_CHESTPLATE", "SKELETOR_LEGGINGS", "SKELETOR_BOOTS"],
    SKELETON_LORD: [
      "SKELETON_LORD_HELMET",
      "SKELETON_LORD_CHESTPLATE",
      "SKELETON_LORD_LEGGINGS",
      "SKELETON_LORD_BOOTS",
    ],
    ZOMBIE_LORD: ["ZOMBIE_LORD_HELMET", "ZOMBIE_LORD_CHESTPLATE", "ZOMBIE_LORD_LEGGINGS", "ZOMBIE_LORD_BOOTS"],
    PERFECT_TIER_12: ["PERFECT_HELMET_12", "PERFECT_CHESTPLATE_12", "PERFECT_LEGGINGS_12", "PERFECT_BOOTS_12"],
    SUPERIOR_DRAGON: [
      "SUPERIOR_DRAGON_HELMET",
      "SUPERIOR_DRAGON_CHESTPLATE",
      "SUPERIOR_DRAGON_LEGGINGS",
      "SUPERIOR_DRAGON_BOOTS",
    ],
    SORROW: ["SORROW_HELMET", "SORROW_CHESTPLATE", "SORROW_LEGGINGS", "SORROW_BOOTS"],
    SHADOW_ASSASSIN: [
      "SHADOW_ASSASSIN_HELMET",
      "SHADOW_ASSASSIN_CHESTPLATE",
      "SHADOW_ASSASSIN_LEGGINGS",
      "SHADOW_ASSASSIN_BOOTS",
    ],
    FINAL_DESTINATION: [
      "FINAL_DESTINATION_HELMET",
      "FINAL_DESTINATION_CHESTPLATE",
      "FINAL_DESTINATION_LEGGINGS",
      "FINAL_DESTINATION_BOOTS",
    ],
    DIVAN: ["DIVAN_HELMET", "DIVAN_CHESTPLATE", "DIVAN_LEGGINGS", "DIVAN_BOOTS"],
    NECROMANCER_LORD: [
      "NECROMANCER_LORD_HELMET",
      "NECROMANCER_LORD_CHESTPLATE",
      "NECROMANCER_LORD_LEGGINGS",
      "NECROMANCER_LORD_BOOTS",
    ],
    WITHER: ["WITHER_HELMET", "WITHER_CHESTPLATE", "WITHER_LEGGINGS", "WITHER_BOOTS"],
    TANK_WITHER: ["TANK_WITHER_HELMET", "TANK_WITHER_CHESTPLATE", "TANK_WITHER_LEGGINGS", "TANK_WITHER_BOOTS"],
    WISE_WITHER: ["WISE_WITHER_HELMET", "WISE_WITHER_CHESTPLATE", "WISE_WITHER_LEGGINGS", "WISE_WITHER_BOOTS"],
    SPEED_WITHER: ["SPEED_WITHER_HELMET", "SPEED_WITHER_CHESTPLATE", "SPEED_WITHER_LEGGINGS", "SPEED_WITHER_BOOTS"],
    POWER_WITHER: ["POWER_WITHER_HELMET", "POWER_WITHER_CHESTPLATE", "POWER_WITHER_LEGGINGS", "POWER_WITHER_BOOTS"],
    RAMPART: ["RAMPART_HELMET", "RAMPART_CHESTPLATE", "RAMPART_LEGGINGS", "RAMPART_BOOTS"],
    REKINDLED_EMBER: [
      "REKINDLED_EMBER_HELMET",
      "REKINDLED_EMBER_CHESTPLATE",
      "REKINDLED_EMBER_LEGGINGS",
      "REKINDLED_EMBER_BOOTS",
    ],
    SHIMMERING_LIGHT: [
      "SHIMMERING_LIGHT_HOOD",
      "SHIMMERING_LIGHT_TUNIC",
      "SHIMMERING_LIGHT_TROUSERS",
      "SHIMMERING_LIGHT_SLIPPERS",
    ],
    BERSERKER: ["BERSERKER_HELMET", "BERSERKER_CHESTPLATE", "BERSERKER_LEGGINGS", "BERSERKER_BOOTS"],
    LAVA_SEA_CREATURE: ["TAURUS_HELMET", "FLAMING_CHESTPLATE", "MOOGMA_LEGGINGS", "SLUG_BOOTS"],
    THUNDER: ["THUNDER_HELMET", "THUNDER_CHESTPLATE", "THUNDER_LEGGINGS", "THUNDER_BOOTS"],
    MAGMA_LORD: ["MAGMA_LORD_HELMET", "MAGMA_LORD_CHESTPLATE", "MAGMA_LORD_LEGGINGS", "MAGMA_LORD_BOOTS"],
    BRONZE_HUNTER: [
      "BRONZE_HUNTER_HELMET",
      "BRONZE_HUNTER_CHESTPLATE",
      "BRONZE_HUNTER_LEGGINGS",
      "BRONZE_HUNTER_BOOTS",
    ],
    SILVER_HUNTER: [
      "SILVER_HUNTER_HELMET",
      "SILVER_HUNTER_CHESTPLATE",
      "SILVER_HUNTER_LEGGINGS",
      "SILVER_HUNTER_BOOTS",
    ],
    GOLD_HUNTER: ["GOLD_HUNTER_HELMET", "GOLD_HUNTER_CHESTPLATE", "GOLD_HUNTER_LEGGINGS", "GOLD_HUNTER_BOOTS"],
    DIAMOND_HUNTER: [
      "DIAMOND_HUNTER_HELMET",
      "DIAMOND_HUNTER_CHESTPLATE",
      "DIAMOND_HUNTER_LEGGINGS",
      "DIAMOND_HUNTER_BOOTS",
    ],
    MAGMA: ["MAGMA_NECKLACE", "GHAST_CLOAK", "BLAZE_BELT", "GLOWSTONE_GAUNTLET"],
    VANQUISHED: [
      "VANQUISHED_MAGMA_NECKLACE",
      "VANQUISHED_GHAST_CLOAK",
      "VANQUISHED_BLAZE_BELT",
      "VANQUISHED_GLOWSTONE_GAUNTLET",
    ],
    MOLTEN: ["MOLTEN_NECKLACE", "MOLTEN_CLOAK", "MOLTEN_BELT", "MOLTEN_BRACELET"],
    AURORA: ["AURORA_HELMET", "AURORA_CHESTPLATE", "AURORA_LEGGINGS", "AURORA_BOOTS"],
    CRIMSON: ["CRIMSON_HELMET", "CRIMSON_CHESTPLATE", "CRIMSON_LEGGINGS", "CRIMSON_BOOTS"],
    FERVOR: ["FERVOR_HELMET", "FERVOR_CHESTPLATE", "FERVOR_LEGGINGS", "FERVOR_BOOTS"],
    TERROR: ["TERROR_HELMET", "TERROR_CHESTPLATE", "TERROR_LEGGINGS", "TERROR_BOOTS"],
    HOLLOW: ["HOLLOW_HELMET", "HOLLOW_CHESTPLATE", "HOLLOW_LEGGINGS", "HOLLOW_BOOTS"],
    MELON: ["MELON_HELMET", "MELON_CHESTPLATE", "MELON_LEGGINGS", "MELON_BOOTS"],
    CROPIE: ["CROPIE_HELMET", "CROPIE_CHESTPLATE", "CROPIE_LEGGINGS", "CROPIE_BOOTS"],
    SQUASH: ["SQUASH_HELMET", "SQUASH_CHESTPLATE", "SQUASH_LEGGINGS", "SQUASH_BOOTS"],
    FERMENTO: ["FERMENTO_HELMET", "FERMENTO_CHESTPLATE", "FERMENTO_LEGGINGS", "FERMENTO_BOOTS"],
    RABBIT: ["RABBIT_HELMET", "RABBIT_CHESTPLATE", "RABBIT_LEGGINGS", "RABBIT_BOOTS"],
    SEYMOUR: ["VELVET_TOP_HAT", "CASHMERE_JACKET", "SATIN_TROUSERS", "OXFORD_SHOES"],
    LOTUS: ["LOTUS_NECKLACE", "LOTUS_CLOAK", "LOTUS_BELT", "LOTUS_BRACELET"],
  },
  aliases: {
    // Weapons
    BONZO_STAFF: "STARRED_BONZO_STAFF",
  },
  inventory: [
    {
      display_name: "Museum",
      rarity: "rare",
      texture_path: "/head/438cf3f8e54afc3b3f91d20a49f324dca1486007fe545399055524c17941f4dc",
      tag: {
        display: {
          Lore: [
            "§7The §9Museum §7is a compendium",
            "§7of all of your items in",
            "§7SkyBlock. Donate items to your",
            "§7Museum to unlock rewards.",
            "",
            "§7Other players can visit your",
            "§7Museum at any time! Display your",
            "§7best items proudly for all to",
            "§7see.",
            "",
          ],
        },
      },
      position: 4,
      progressType: "total",
    },
    {
      display_name: "Weapons",
      id: 276,
      damage: 0,
      rarity: "uncommon",
      tag: {
        display: {
          Lore: ["§7View all of the §6Weapons §7that", "§7you have donated to the", "§7§9Museum§7!", ""],
        },
      },
      position: 19,
      inventoryType: "weapons",
      containsItems: [
        {
          display_name: "Weapons",
          id: 276,
          damage: 0,
          rarity: "uncommon",
          tag: {
            display: {
              Lore: ["§7View all of the §6Weapons §7that", "§7you have donated to the", "§7§9Museum§7!", ""],
            },
          },
          position: 4,
        },
        ...categoryInventory,
      ],
      numPagesContainsInventory: 1,
      progressType: "weapons",
    },
    {
      display_name: "Armor Sets",
      id: 311,
      damage: 0,
      rarity: "uncommon",
      tag: {
        display: {
          Lore: ["§7View all of the §9Armor Sets", "§9§7that you have donated to the", "§7§9Museum§7!", ""],
        },
      },
      position: 21,
      inventoryType: "armor",
      containsItems: [
        {
          display_name: "Armor Sets",
          id: 311,
          damage: 0,
          rarity: "uncommon",
          tag: {
            display: {
              Lore: ["§7View all of the §9Armor Sets", "§9§7that you have donated to the", "§7§9Museum§7!", ""],
            },
          },
          position: 4,
        },
        ...categoryInventory,
      ],
      numPagesContainsInventory: 1,
      progressType: "armor",
    },
    {
      display: "Rarities",
      rarity: "uncommon",
      texture_path: "/head/86addbd5dedad40999473be4a7f48f6236a79a0dce971b5dbd7372014ae394d",
      tag: {
        display: {
          Lore: ["§7View all of the §5Rarities", "§5§7that you have donated to the", "§7§9Museum§7!", ""],
        },
      },
      position: 23,
      inventoryType: "rarities",
      containsItems: [
        {
          display: "Rarities",
          rarity: "uncommon",
          texture_path: "/head/86addbd5dedad40999473be4a7f48f6236a79a0dce971b5dbd7372014ae394d",
          tag: {
            display: {
              Lore: ["§7View all of the §5Rarities", "§5§7that you have donated to the", "§7§9Museum§7!", ""],
            },
          },
          position: 4,
        },
        ...categoryInventory,
      ],
      numPagesContainsInventory: 1,
      progressType: "rarities",
    },
    {
      display_name: "Special Items",
      id: 354,
      damage: 0,
      rarity: "uncommon",
      tag: {
        display: {
          Lore: [
            "§7View all of the §dSpecial Items",
            "§d§7that you have donated to the",
            "§7§9Museum§7!",
            "",
            "§7These items don't count towards",
            "§7Museum progress and rewards, but",
            "§7are cool nonetheless. Items that",
            "§7are §9rare §7and §6prestigious",
            "§6§7fit into this category, and",
            "§7can be displayed in the Main",
            "§7room of the Museum.",
            "",
          ],
        },
      },
      position: 25,
      inventoryType: "special",
      containsItems: [
        {
          display_name: "Special Items",
          id: 354,
          damage: 0,
          rarity: "uncommon",
          tag: {
            display: {
              Lore: [
                "§7View all of the §dSpecial Items",
                "§d§7that you have donated to the",
                "§7§9Museum§7!",
                "",
                "§7These items don't count towards",
                "§7Museum progress and rewards, but",
                "§7are cool nonetheless. Items that",
                "§7are §9rare §7and §6prestigious",
                "§6§7fit into this category, and",
                "§7can be displayed in the Main",
                "§7room of the Museum.",
                "",
              ],
            },
          },
          position: 4,
        },
        ...categoryInventory,
      ],
      numPagesContainsInventory: 1,
      progressType: "special",
    },
    {
      display_name: "Museum Appraisal",
      id: 264,
      damage: 0,
      rarity: "legendary",
      tag: {
        display: {
          Lore: [
            "§7§6Madame Goldsworth §7offers an",
            "§7appraisal service for Museums.",
            "§7When unlocked, she will appraise",
            "§7the value of your Museum each",
            "§7time you add or remove items.",
            "",
            "§7This service also allows you to",
            "§7appear on the §6Top Valued",
            "§6§7filter in the §9Museum",
            "§9Browser§7.",
            "",
          ],
        },
      },
      position: 40,
      progressType: "appraisal",
    },
    {
      display_name: "Edit NPC Tags",
      id: 421,
      damage: 0,
      rarity: "uncommon",
      tag: {
        display: {
          Lore: [
            "§7Edit the tags that appear above",
            "§7your NPC. Show off your SkyBlock",
            "§7progress with tags showing your",
            "§7highest collection, best Skill,",
            "§7and more!",
            "",
            "§cCOMING SOON",
          ],
        },
      },
      position: 45,
    },
    {
      display_name: "Museum Rewards",
      id: 41,
      damage: 0,
      rarity: "legendary",
      tag: {
        display: {
          Lore: [
            "§7Each time you donate an item to",
            "§7your Museum, the §bCurator",
            "§b§7will reward you.",
            "",
            "§7§dSpecial Items §7do not count",
            "§7towards your Museum rewards",
            "§7progress.",
            "",
            "§7Currently, most rewards are",
            "§7§ccoming soon§7, but you can",
            "§7view them anyway.",
          ],
        },
      },
      position: 48,
    },
    {
      display_name: "Close",
      id: 166,
      damage: 0,
      rarity: "special",
      tag: {
        display: {
          Lore: [],
        },
      },
      position: 49,
    },
    {
      display_name: "Museum Browser",
      id: 323,
      damage: 0,
      rarity: "uncommon",
      tag: {
        display: {
          Lore: ["§7View the Museums of your", "§7friends, top valued players, and", "§7more!"],
        },
      },
      position: 50,
    },
  ],
  item_slots: [
    10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 22, 23, 24, 25, 28, 29, 30, 31, 32, 33, 34, 37, 38, 39, 40, 41, 42, 43,
  ],
  missing_item: {
    weapons: {
      display_name: null,
      id: 351,
      damage: 8,
      rarity: "special",
      tag: {
        display: {
          Lore: ["§7Click on this item in your", "§7inventory to add it to your", "§7§9Museum§7!"],
        },
      },
    },
    armor: {
      display_name: null,
      id: 351,
      damage: 8,
      rarity: "special",
      tag: {
        display: {
          Lore: [
            "§7Click on an armor piece in your",
            "§7inventory that belongs to this",
            "§7armor set to donate the full set",
            "§7to your Museum.",
          ],
        },
      },
    },
    rarities: {
      display_name: null,
      id: 351,
      damage: 8,
      rarity: "special",
      tag: {
        display: {
          Lore: ["§7Click on this item in your", "§7inventory to add it to your", "§7§9Museum§7!"],
        },
      },
    },
    special: null,
  },
  higher_tier_donated: {
    display_name: null,
    id: 351,
    damage: 10,
    rarity: "special",
    tag: {
      display: {
        Lore: ["§7Donated as higher tier"],
      },
    },
  },
};

export function getMuseumItems() {
  const { armor, weapons, rarities } = MUSEUM;

  return [...armor, ...weapons, ...rarities];
}
