export const SACKS = {
  AGRONOMY_SACK: {
    items: [
      "WHEAT",
      "SEEDS",
      "CARROT_ITEM",
      "POTATO_ITEM",
      "PUMPKIN",
      "MELON",
      "RED_MUSHROOM",
      "BROWN_MUSHROOM",
      "INK_SACK:3",
      "CACTUS",
      "SUGAR_CANE",
      "NETHER_STALK",
    ],
    texture: "ef835b8941fe319931749b87fe8e84c5d1f4a271b5fbce5e700a60004d881f79",
  },
  ENCHANTED_AGRONOMY_SACK: {
    items: [
      "ENCHANTED_BREAD",
      "ENCHANTED_BROWN_MUSHROOM",
      "ENCHANTED_CACTUS",
      "ENCHANTED_CARROT",
      "ENCHANTED_COCOA",
      "ENCHANTED_MELON",
      "ENCHANTED_NETHER_STALK",
      "ENCHANTED_POTATO",
      "ENCHANTED_PUMPKIN",
      "ENCHANTED_RED_MUSHROOM",
      "ENCHANTED_SEEDS",
      "ENCHANTED_SUGAR",
    ],
    texture: "184d2ff1e177357574f9f71e19397fff3a210a94e78c0d2a4360cc5df1eb807b",
  },
  HUSBANDRY_SACK: {
    items: ["FEATHER", "LEATHER", "PORK", "RAW_CHICKEN", "MUTTON", "RABBIT", "RAW_BEEF", "RABBIT_HIDE", "RABBIT_FOOT"],
    texture: "c73087f1e654b1682733584a44097587fb942e1f343aae8307bd7dac84e843ab",
  },
  ENCHANTED_HUSBANDRY_SACK: {
    items: [
      "ENCHANTED_FEATHER",
      "ENCHANTED_LEATHER",
      "ENCHANTED_PORK",
      "ENCHANTED_RAW_CHICKEN",
      "ENCHANTED_EGG",
      "ENCHANTED_MUTTON",
      "ENCHANTED_RABBIT",
      "ENCHANTED_RAW_BEEF",
      "ENCHANTED_RABBIT_HIDE",
      "ENCHANTED_RABBIT_FOOT",
    ],
    texture: "746a6063263ba7208a2a06cef73234791c92d5f67080a365508b02483eefaf9a",
  },
  MINING_SACK: {
    items: [
      "COBBLESTONE",
      "COAL",
      "IRON_INGOT",
      "GOLD_INGOT",
      "DIAMOND",
      "INK_SACK:4",
      "EMERALD",
      "REDSTONE",
      "QUARTZ",
      "OBSIDIAN",
      "GLOWSTONE_DUST",
      "GRAVEL",
      "ICE",
      "NETHERRACK",
      "SAND",
      "ENDER_STONE",
      "MITHRIL_ORE",
      "HARD_STONE",
      "TITANIUM_ORE",
      "TREASURITE",
      "STARFALL",
    ],
    texture: "915fcebbbe02fdb72acd2095d9edfcea095e604b3682db88963b5b83b2939b67",
  },
  ENCHANTED_MINING_SACK: {
    items: [
      "ENCHANTED_COAL",
      "ENCHANTED_COBBLESTONE",
      "ENCHANTED_DIAMOND",
      "ENCHANTED_EMERALD",
      "ENCHANTED_ENDSTONE",
      "ENCHANTED_FLINT",
      "ENCHANTED_GLOWSTONE_DUST",
      "ENCHANTED_GOLD",
      "ENCHANTED_HARD_STONE",
      "ENCHANTED_IRON",
      "ENCHANTED_LAPIS_LAZULI",
      "ENCHANTED_MITHRIL",
      "ENCHANTED_NETHERRACK",
      "ENCHANTED_OBSIDIAN",
      "ENCHANTED_QUARTZ",
      "ENCHANTED_REDSTONE",
      "ENCHANTED_SAND",
      "ENCHANTED_TITANIUM",
    ],
    texture: "eedc69fefad184ee8c9186928da982addfd783bed98d95083408bf419e0cccd0",
  },
  GEMSTONE_SACK: {
    items: [
      "ROUGH_AMBER_GEM",
      "FLAWED_AMBER_GEM",
      "FINE_AMBER_GEM",
      "FLAWLESS_AMBER_GEM",
      "PERFECT_AMBER_GEM",
      "ROUGH_TOPAZ_GEM",
      "FLAWED_TOPAZ_GEM",
      "FINE_TOPAZ_GEM",
      "FLAWLESS_TOPAZ_GEM",
      "PERFECT_TOPAZ_GEM",
      "ROUGH_SAPPHIRE_GEM",
      "FLAWED_SAPPHIRE_GEM",
      "FINE_SAPPHIRE_GEM",
      "FLAWLESS_SAPPHIRE_GEM",
      "PERFECT_SAPPHIRE_GEM",
      "ROUGH_AMETHYST_GEM",
      "FLAWED_AMETHYST_GEM",
      "FINE_AMETHYST_GEM",
      "FLAWLESS_AMETHYST_GEM",
      "PERFECT_AMETHYST_GEM",
      "ROUGH_JASPER_GEM",
      "FLAWED_JASPER_GEM",
      "FINE_JASPER_GEM",
      "FLAWLESS_JASPER_GEM",
      "PERFECT_JASPER_GEM",
      "ROUGH_RUBY_GEM",
      "FLAWED_RUBY_GEM",
      "FINE_RUBY_GEM",
      "FLAWLESS_RUBY_GEM",
      "PERFECT_RUBY_GEM",
      "ROUGH_JADE_GEM",
      "FLAWED_JADE_GEM",
      "FINE_JADE_GEM",
      "FLAWLESS_JADE_GEM",
      "PERFECT_JADE_GEM",
      "ROUGH_OPAL_GEM",
      "FLAWED_OPAL_GEM",
      "FINE_OPAL_GEM",
      "FLAWLESS_OPAL_GEM",
      "PERFECT_OPAL_GEM",
    ],
    texture: "95ba804b7ae92c65b2f41d18be899a3bd139772e3e3c81c2fc8addbb27536952",
  },
  COMBAT_SACK: {
    items: [
      "ROTTEN_FLESH",
      "BONE",
      "STRING",
      "SPIDER_EYE",
      "SULPHUR",
      "ENDER_PEARL",
      "GHAST_TEAR",
      "SLIME_BALL",
      "BLAZE_ROD",
      "MAGMA_CREAM",
    ],
    texture: "1c13c4774c82c07071e6d1408717b1e3eac56186042a5803fc174452e32a254a",
  },
  ENCHANTED_COMBAT_SACK: {
    items: [
      "ENCHANTED_BLAZE_POWDER",
      "ENCHANTED_BONE",
      "ENCHANTED_ENDER_PEARL",
      "ENCHANTED_GHAST_TEAR",
      "ENCHANTED_GUNPOWDER",
      "ENCHANTED_MAGMA_CREAM",
      "ENCHANTED_ROTTEN_FLESH",
      "ENCHANTED_SLIME_BALL",
      "ENCHANTED_SPIDER_EYE",
      "ENCHANTED_STRING",
    ],
    texture: "c2a3420697256517d5361b3463019647c0689725b3489f9dd24a22ddd40bd41f",
  },
  FORAGING_SACK: {
    items: [
      "LOG",
      "LOG:1",
      "LOG:2",
      "LOG_2:1",
      "LOG_2",
      "LOG:3",
      "SAPLING",
      "SAPLING:1",
      "SAPLING:2",
      "SAPLING:5",
      "SAPLING:4",
      "SAPLING:3",
      "APPLE",
    ],
    texture: "2c6e24df498ba4a589c259d9fc0d3db348f93cdf26a5fe461571c1da706efaf3",
  },
  ENCHANTED_FORAGING_SACK: {
    items: [
      "ENCHANTED_OAK_LOG",
      "ENCHANTED_SPRUCE_LOG",
      "ENCHANTED_BIRCH_LOG",
      "ENCHANTED_DARK_OAK_LOG",
      "ENCHANTED_ACACIA_LOG",
      "ENCHANTED_JUNGLE_LOG",
    ],
    texture: "35326464c6a79362730d79fe4611b911353c1b3c5144177773591357f1cd5ca1",
  },
  FISHING_SACK: {
    items: [
      "RAW_FISH",
      "RAW_FISH:1",
      "RAW_FISH:2",
      "RAW_FISH:3",
      "PRISMARINE_SHARD",
      "PRISMARINE_CRYSTALS",
      "CLAY",
      "WATER_LILY",
      "INK_SACK",
      "SPONGE",
    ],
    texture: "f8f68669351a6fc7156ecfe3300ba94efe0766e24bed8785cf64a9f95435134b",
  },
  ENCHANTED_FISHING_SACK: {
    items: [
      "ENCHANTED_CLAY_BALL",
      "ENCHANTED_CLOWNFISH",
      "ENCHANTED_INK_SACK",
      "ENCHANTED_PUFFERFISH",
      "ENCHANTED_RAW_FISH",
      "ENCHANTED_RAW_SALMON",
      "ENCHANTED_SPONGE",
      "ENCHANTED_WATER_LILY",
      "ENCHANTED_PRISMARINE_CRYSTALS",
      "ENCHANTED_PRISMARINE_SHARD",
    ],
    texture: "ee2469de7f75d2e0a8b3b0c734a2b470782b604d1feb0172b4a72a77cb5bbda2",
  },
  LAVA_FISHING_SACK: {
    items: [
      "MAGMA_FISH",
      "MAGMA_CREAM",
      "COAL",
      "BLAZE_POWDER",
      "NETHERRACK",
      "MOOGMA_PELT",
      "PYROCLASTIC_SCALE",
      "FLAMING_HEART",
      "LUMP_OF_MAGMA",
      "CUP_OF_BLOOD",
      "ORB_OF_ENERGY",
      "HORN_OF_TAURUS",
    ],
    texture: "da2a951592cc26cf5b6d9f66ae034916f9d2e97216d43b3fa11c979afd7df1ad",
  },
  NETHER_SACK: {
    items: [
      "SULPHUR_ORE",
      "SAND:1",
      "MYCEL",
      "ECTOPLASM",
      "NETHERRACK",
      "MAGMA_CREAM",
      "BLAZE_ROD",
      "GHAST_TEAR",
      "QUARTZ",
      "GLOWSTONE_DUST",
      "NETHER_STALK",
      "SPECTRE_DUST",
      "BLAZE_ASHES",
      "MUTATED_BLAZE_ASHES",
      "WITHER_SOUL",
      "MAGMA_CHUNK",
      "BEZOS",
      "BURNING_EYE",
      "TENTACLE_MEAT",
      "DIGESTED_MUSHROOMS",
      "KADA_LEAD",
      "MAGMAG",
      "GAZING_PEARL",
      "LEATHER_CLOTH",
      "SPELL_POWDER",
      "COMPACT_OOZE",
      "LUMINO_FIBER",
      "HALLOWED_SKULL",
      "CORRUPTED_FRAGMENT",
    ],
    texture: "e345875e921a145f92038858aeecc3c2f083441ebc5c8265d31a281d268e365b",
  },
  DUNGEON_SACK: {
    items: ["SPIRIT_LEAP", "DUNGEON_TRAP", "INFLATABLE_JERRY", "DUNGEON_DECOY"],
    texture: "fb96c585ccd35f073da38d165cb9bb18ff136f1a184eee3f44725354640ebbd4",
  },
  RUNE_SACK: {
    items: ["RUNE"],
    texture: "e91eb4ee3ecce3447483a1f151c11facc9de25577ab7b51fbf3d9c2b2a4b69fc",
  },
  SLAYER_SACK: {
    items: [
      "TARANTULA_WEB",
      "SPIDER_CATALYST",
      "UNDEAD_CATALYST",
      "REVENANT_CATALYST",
      "NULL_SPHERE",
      "RAW_SOULFLOW",
      "SOULFLOW",
      "DERELICT_ASHE",
      "CRUDE_GABAGOOL",
    ],
    texture: "c0ccbd15d76a748e08926ef6d21dc3e54d9adec766cc25019531a493b1fd4b44",
  },
  SPOOKY_SACK: {
    items: ["GREEN_CANDY", "PURPLE_CANDY", "PUMPKIN_GUTS", "ECTOPLASM", "WEREWOLF_SKIN"],
    texture: "12ef39437d7d43a034c5a40b974e8d2c6734a218c76485d04910f507bdc2e809",
  },
  WINTER_SACK: {
    items: [
      "WHITE_GIFT",
      "GREEN_GIFT",
      "RED_GIFT",
      "SNOW_BLOCK",
      "ENCHANTED_SNOW_BLOCK",
      "SNOW_BALL",
      "ICE",
      "ENCHANTED_ICE",
      "PACKED_ICE",
      "ENCHANTED_PACKED_ICE",
      "HUNK_OF_ICE",
      "HUNK_OF_BLUE_ICE",
    ],
    texture: "ab339b1cd40053defd7d3528e01fea876d41b42f9d9268461da79f5f66771236",
  },
};

export const ITEM_SACKS = {
  HUNK_OF_BLUE_ICE: "BLUE_ICE_HUNK",
  HUNK_OF_ICE: "ICE_HUNK",
};
