export const stats_colors = {
  ability_damage: "c",
  bonus_attack_speed: "e",
  crit_chance: "9",
  crit_damage: "9",
  defense: "a",
  farming_fortune: "6",
  ferocity: "c",
  foraging_fortune: "6",
  health: "c",
  intelligence: "b",
  magic_find: "b",
  mining_fortune: "6",
  mining_speed: "6",
  pet_luck: "d",
  powder: "9",
  pristine: "5",
  sea_creature_chance: "3",
  speed: "f",
  strength: "c",
  true_defense: "f",
};
