export const stats_symbols = {
  ability_damage: "๑",
  attack_speed: "⚔",
  bonus_attack_speed: "⚔",
  crit_chance: "☣",
  crit_damage: "☠",
  defense: "❈",
  farming_fortune: "☘",
  ferocity: "⫽",
  foraging_fortune: "☘",
  health: "❤",
  intelligence: "✎",
  magic_find: "✯",
  mining_fortune: "☘",
  mining_speed: "⸕",
  pet_luck: "♣",
  powder: "᠅", // todo: missing icon in icomoon font
  pristine: "✧",
  sea_creature_chance: "α",
  speed: "✦",
  strength: "❁",
  true_defense: "❂", // todo: missing icon in icomoon font
};

export const stats_colors = {
  ability_damage: "c",
  attack_speed: "e",
  bonus_attack_speed: "e",
  crit_chance: "9",
  crit_damage: "9",
  defense: "a",
  farming_fortune: "6",
  ferocity: "c",
  foraging_fortune: "6",
  health: "c",
  intelligence: "b",
  magic_find: "b",
  mining_fortune: "6",
  mining_speed: "6",
  pet_luck: "d",
  powder: "9",
  pristine: "5",
  sea_creature_chance: "3",
  speed: "f",
  strength: "c",
  true_defense: "f",
};
