module.exports = {
    item_tags: {
        SUPER_COMPACTOR_3000: "sc3000 sc3k",
        ENCHANTED_LAPIS_LAZULI: "elapis",
        ENCHANTED_IRON_INGOT: "eiron",
        ENCHANTED_IRON_BLOCK: "eiron",
        ENCHANTED_STRING: "estring",
        ENCHANTED_ROTTEN_FLESH: "eflesh erotten",
        ENCHANTED_WET_SPONGE: "ewet",
        ENCHANTED_DIAMOND: "edia",
        ENCHANTED_DIAMOND_BLOCK: "edb",
        ENCHANTED_LAVA_BUCKET: "elava",
        ENCHANTED_GLOWSTONE_DUST: "edust",
        ENCHANTED_GLOWSTONE: "eblock block",
        ENCHANTED_REDSTONE_LAMP: "elamp",
        ENCHANTED_REDSTONE_DUST: "edust",
        ENCHANTED_REDSTONE_BLOCK: "eblock",
        CATALYST: "cata",
        SUPERIOR_FRAGMENT: "sup frag drag",
        STRONG_FRAGMENT: "frag drag",
        PROTECTOR_FRAGMENT: "frag drag",
        WISE_FRAGMENT: "frag drag",
        YOUNG_FRAGMENT: "frag drag",
        OLD_FRAGMENT: "old frag drag",
        UNSTABLE_FRAGMENT: "frag drag",
        ENCHANTED_GOLD: "egold ingot",
        ENCHANTED_GOLD_BLOCK: "egold",
        ENCHANTED_COAL: "ecoal",
        ENCHANTED_COAL_BLOCK: "ecoal",
        ENCHANTED_COBBLESTONE: "ecobble",
        INK_SACK: "eink sack",
        TARANTULA_WEB: "tara",
        ENCHANTED_POTATO: "epotato",
        ENCHANTED_SLIME_BALL: "eslime",
        ENCHANTED_SLIME_BLOCK: "eslime",
        ENCHANTED_BIRCH_LOG: "ebirch",
        ENCHANTED_SUGAR: "esugar",
        ENCHANTED_MELON: "emelon",
        ENCHANTED_BLAZE_ROD: "erod",
        ENCHANTED_CAKE: "ecake",
        ENCHANTED_SNOW_BLOCK: "esnow",
        ENCHANTED_CACTUS_GREEN: "ecactus",
        ENCHANTED_COOKIE: "ecookie",
        ENCHANTED_SAND: "esand",
        ENCHANTED_COCOA: "ecocoa",
        ENCHANTED_LEATHER: "eleather",
        ENCHANTED_SPONGE: "esponge",
        ENCHANTED_GRILLED_PORK: "epork",
        ENCHANTED_DARK_OAK_LOG: "edoak doak",
        ENCHANTED_ACACIA_LOG: "eacacia",
        ENCHANTED_SPRUCE_LOG: "espruce",
        ENCHANTED_RAW_CHICKEN: "echicken",
        ENCHANTED_WATER_LILY: "elily",
        ENCHANTED_SUGAR_CANE: "ecane",
        ENCHANTED_FERMENTED_SPIDER_EYE: "eferm ferm",
        ENCHANTED_JUNGLE_LOG: "ejungle",
        ENCHANTED_OAK_LOG: "eoak",
        ENCHANTED_CLAY_BALL: "eclay",
        REVENANT_VISCERA: "rev",
        ENCHANTED_HAY_BLOCK: "ehay",
        ENCHANTED_PAPER: "epaper",
        ENCHANTED_BONE: "ebone",
        ENCHANTED_RABBIT_FOOT: "efoot",
        ENCHANTED_ICE: "eice",
        ENCHANTED_OBSIDIAN: "eobsidian",
        ENCHANTED_QUARTZ: "equartz",
        ENCHANTED_RAW_FISH: "efish",
        ENCHANTED_RAW_BEEF: "ecow",
        ENCHANTED_FEATHER: "efeather",
        ENCHANTED_CARROT: "ecarrot",
        ENCHANTED_PUMPKIN: "epumpkin",
        ENCHANTED_COOKED_FISH: "ecooked",
        ENCHANTED_MAGMA_CREAM: "emagma ecream",
        ENCHANTED_COOKED_MUTTON: "emutton",
        ENCHANTED_BLAZE_POWDER: "eblaze",
        ENCHANTED_BAKED_POTATO: "ebaked",
        SUMMONING_EYE: "sum",
        ENDER_STONE: "endstone",
        ENCHANTED_ENDSTONE: "endstone",
        HOT_POTATO_BOOK: "hpb",
        RABBIT_FOOT: 'rabbit'
    }
};
