export const specialEnchants = new Set([
  "Sharpness VII",
  "Sharpness VI",
  "Giant Killer VII",
  "Giant Killer VI",
  "Bane of Arthropods VII",
  "Bane of Arthropods VI",
  "Critical VII",
  "Critical VI",
  "Ender Slayer VII",
  "Ender Slayer VI",
  "Experience IV",
  "Life Steal V",
  "Life Steal IV",
  "Looting V",
  "Looting IV",
  "Luck VII",
  "Luck VI",
  "Scavenger V",
  "Scavenger IV",
  "Smite VII",
  "Smite VI",
  "Vampirism VI",
  "Power VII",
  "Power VI",
  "Growth VII",
  "Growth VI",
  "Blast Protection VII",
  "Blast Protection VI",
  "Fire Protection VII",
  "Fire Protection VI",
  "Projectile Protection VII",
  "Projectile Protection VI",
  "Protection VII",
  "Protection VI",
  "True Protection I",
  "Sugar Rush III",
  "Efficiency VI",
  "Angler VI",
  "Caster VI",
  "Frail VI",
  "Luck of the Sea VI",
  "Lure VI",
  "Magnet VI",
  "Spiked Hook VI",
  "Dragon Hunter V",
  "Feather Falling X",
  "Feather Falling XX",
  "Infinite Quiver X",
  "Thorns VI",
  "Expertise X",
  "Thunderlord VI",
  "Lethality VI",
  "Compact X",
  "Cultivating X",
  "First Strike V",
  "Execute VI",
  "Cubism VI",
  "Venomous VI",
  "Cleave VI",
  "Harvesting VI",
  "Fortune IV",
  "Pristine V",
]);
